apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgDJ0/g3xG+UzW2UjdZgH0j+2Y3jVblOIVIaxM7aNRaC0AUgNkURZZwRAmYRtH5Hz4i/Ov6Te7jm7bvIAhP4Tfl9Bu2W5xn/tJ+S0rbEp6t925yZFVM/oYGUZH/l2zcpGRRhyIqLRml0cartwNNu78lE28qvd9M+TrcnA9tqA+oWT/0eS8+xL9Hw9difYjawOpkezh1kXTQ3epsMVu6kQg2L68K7PN1ZLFgAc7+vLpT/tPuPjSlUNnkxt4aEgRqB5yH7h3FxgSiCZq0d4fE9NMZlSScryXYcW8jAAC7QbdKXFWHDk8CQ5YgZcJPZRSDFJjr7AIQFE0uqPymk4cLK6uP12YNqP6WIGo1xU384O0y1GyISr3oiEJqbLGNPo49+oB0zQX5EHuSsgFBgICh9QvYwhQMDfuyNKnzt/it5kOCgPJofccosHSm50wRrsW6O4SmyyaiJdu+6CYqpBSu6Q1xujdDCRF9zNFHrwEtZ1Hv2oZ4h0Ih2JHrAOljHCxLq5zw9wCSK9J2/UB2iWjwK1BxpF+f7WfQ+U40mkb4fvUk6SdIFwAjmcr1vRJmvLdUVyFt8uA9wpa5UWVFrLKbYUamcLvl4s9a4+91AfbrFm/lWoXTlHoBVaIudRgOCeIVchtp6ZyQTSepezxUT3+R8RZpD6a8tBNsSVPx2LEC8BSG1quy5D4/Bu18OnQInXssDTdbIlPx/rx6tjIO7ddh+BIyQgWTQQ4yV6twaYqFkqrFoicGCJtU97nC3NoEnIP9LnNZuQvuwjEoSogXa22Exh2IXaw==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

